### PR TITLE
Popper is now Floating UI. Migration

### PR DESCRIPTION
**Pull request by Atrue**
Since Popper.js has become @floating-ui and the API has changed a lot it becomes harder to support both versions (for example the latest version of TippyJS still using Popper.js), so instead of depending on a specific external version I made the extension allowing users to use any Popper library with providing `popperFactory` function during module registration.
It means users can still use the outdated Popper.js or TippyJS after upgrading the extension.

I've updated demo examples and READMI, but the only step is needed for the user is to provide `popperFactory`. Here is an example of the factory for a new `@floating-ui` version:
```js
import cytoscape from 'cytoscape';
import cytoscapePopper from 'cytoscape-popper';
import {computePosition} from '@floating-ui/dom';

function popperFactory(ref, content, opts) {
   function update() {
       computePosition(ref, content, opts).then(({x, y}) => {
           Object.assign(content.style, {
               left: `${x}px`,
               top: `${y}px`,
           });
       });
   }
   update();
   return { update };
}

cytoscape.use(cytoscapePopper(popperFactory));
```
Note about this factory: I left the only `update` method for the popper instance as it looks like other methods (like `destroy`) are not needed there as a new middleware behaviour has no side effects https://floating-ui.com/docs/middleware

I've also moved typings file from `@types/cytoscape-popper` here to have everything in one place and upgrade it in the same version

### CODE REVIEW

**Comment by maxkfranz** [comment]
Nice. I'll try to review later today. 

Does your PR include/update demos for the cases you mentioned (legacy, legacy+tippy, new)?  That would be useful for extension consumers and also expedite review.

**Comment by Atrue** [comment]
@maxkfranz You can look at `demo.html` (new @floating-ui) and `demo-tippy.html` (tippy@6 + popperjs@2).

Currently there are no examples for outdated popperjs@2 in the project, but I can add this snippet to the README:
```
function popperFactory(ref, content, opts) {
	return Popper.createPopper(ref, content, opts);
}

cytoscape.use(cytoscapePopper(popperFactory));
```

**Comment by Atrue** [comment]
@maxkfranz Feel free to ask me anything about this. I can add more examples if needed.

You can also read more about migration here https://floating-ui.com/docs/migration. Here is an example of middleware to use to match the Popper.js behaviour:
```
computePosition(referenceEl, floatingEl, {
  placement: ‘top’,
  middleware: [flip(), shift({limiter: limitShift()})],
}).then(({x, y}) => {
  // ...
});
```
And an example of using transform style instead of pixel positioning https://floating-ui.com/docs/misc

**Comment by maxkfranz** [comment]
Will review MondayOn Oct 13, 2023, at 01:50, Atrue ***@***.***> wrote:﻿
@maxkfranz Feel free to ask me anything about this. I can add more examples if needed.
You can also read more about migration here https://floating-ui.com/docs/migration. Here is an example of middleware to use to match the Popper.js behaviour:
computePosition(referenceEl, floatingEl, {
  placement: ‘top’,
  middleware: [flip(), shift({limiter: limitShift()})],
}).then(({x, y}) => {
  // ...
});

And an example of using transform style instead of pixel positioning https://floating-ui.com/docs/misc

**Comment by maxkfranz** [comment]
I’ve been really busy.  I’ll try to set aside time to review this today or tomorrow.

**Comment by Atrue** [comment]
@maxkfranz Do you have any news? Just a note, my changes allow to use any version of Popper library so it will be safe to upgrade for consumers

**Comment by maxkfranz** [comment]
I'll give this a look some time this week.

**Comment by maxkfranz** [comment]
I checked out the PR branch, and here is some initial feedback:

1. Overall, it looks good.
2. There's a yarn lock file, and there's no package-lock.json file for npm.  All the extensions and core lib use npm currently, so moving to yarn is out for now.
3. There should be initialisation code in each of the Popper examples in the readme.  A lot of people won't be able to follow along with the examples unless they're complete from start to finish.
4. It's good that the main demo file uses the new Floating UI lib.  However, it would be useful to have a Popper 2 demo file.  The Tippy demo covers the Popper 2 case a bit, but it's not quite the same, and again lots of people won't be able to follow along unless the demo can be used verbatim.

Great PR.  Thanks for bumping it up.

It looks like there's mostly documentation and build issues to resolve.  Once they're sorted out, I'll merge this in and release.  Make sure to `@mention` me, as I get too many notifications and the `@mentions` are faster to check.

**Comment by Atrue** [comment]
@maxkfranz Thank you for the feedback

1. Replaced back to package-lock.json (it automatically updated to lockfileVersion=2)

2. Added a demo-popper.html file for Popper.js@2 example

3. Added more examples in Readme

**Comment by Atrue** [comment]
@maxkfranz looking forward to your feedback on this, when possible!

**Comment by maxkfranz** [comment]
@ATrue, I'll try to set aside time to review this on Thursday.

Are the TS dependencies strictly necessary?  It looks like there's already a statically-generated type file in your PR and the source isn't TS.

**Comment by maxkfranz** [comment]
@chrtannus, would you check out this PR and verify that the demos are working correctly?

It looked OK to me at first glance several commits before, but I’d like to have it confirmed before we merge this in. 

I won’t have time to look at this PR until late next week, so I appreciate your help in reviewing the demos so @Atrue can get some timely feedback. 

Thanks

**Comment by Atrue** [comment]
@maxkfranz, @cannin Regarding TS, I mentioned it that `cytoscape-popper.d.ts` file is moved from `@types/cytoscape-popper` lib and modified to the new api to have everything in one place and upgrading it with the same version.
There is also a note in the README file

**Review by chrtannus — APPROVED** [review]
I tested all 3 demo HTML pages (dragging nodes, panning, zooming, window resizing) and they all look the same as before. I did not notice any issues.

**Comment by chrtannus** [comment]
Just one unrelated issue: I had a hard time building the project. I got a few errors like this:

```
npm ERR! network request to https://artifactory.artifacts.avp.ru/artifactory/api/npm/common-public/typescript/typescript-3.8.0.tgz failed,
    reason: getaddrinfo ENOTFOUND artifactory.artifacts.avp.ru
```

I had to update `typescript` to version `^5.3.3` and install `lodash` to fix them.
We may want to update these and other dependencies that are too old.

**Comment by Atrue** [comment]
@chrtannus Sorry, it's my fault with registries. I’ve updated the lock file. Can you check it again?
As for the versions, as you can see there are no more `dependencies` in the `package.json` file, all the deps are dev only so they are not used by the consumers. So you can update all these libs later without touching the release npm version.

**Comment by chrtannus** [comment]
@Atrue Don't worry about it. It works now. Thanks for the explanation. Great work!

**Comment by maxkfranz** [comment]
Merged.  Release upcoming

**Comment by maxkfranz** [comment]
Released a new major version, as this PR corresponds to large changes re. compatibility.

**Pull request merged**
